### PR TITLE
iOS: bump min version

### PR DESCRIPTION
**Pull request by warmenhoven**

### CODE REVIEW

**Comment by phcoder** [comment]
Can you tell why this is necessary? Why do we need to drop old iOS?

**Comment by warmenhoven** [comment]
Sorry, meant to include the reasoning for this in the PR description.

The way I got to this PR was by putting together the iOS App Store build. The App Store was rejecting this core specifically because it lacked an LC_ENCRYPTION_INFO load command (download and unzip https://buildbot.libretro.com/nightly/apple/ios-arm64/latest/freechaf_libretro_ios.dylib.zip and run `otool -l <dylib> | grep LC_ENCR` and you'll see it's empty, it should be present, and is on the other cores). When I build the core using Xcode 15.3.0, the LC_ENCRYPTION_INFO_64 command is present. However, the libretro Mac builder is running Xcode 12.2, and when it builds the core, that command is not present.

Xcode 12.2 actually only supports back to iOS 9, so moving the min version up to 8 is already a little bit misleading as the core wouldn't actually support a version that far back. Also, the first iPhone that was arm64 was the iPhone 5S, which debuted with iOS 7.

I can change the minimum version to 7, which also fixes this, if that's preferred. Setting it to 6 or lower causes the LC_ENCRYPTION_INFO to be lost.

**Comment by warmenhoven** [comment]
Oh and one other thing, if you look four lines up from my diff, you'll see that for armv7 it's also setting the minimum version to 8.

**Comment by LibretroAdmin** [comment]
@warmenhoven will send a followup PR after this one is merged that will make it possible for users to still compile for older iOS versions.

**Pull request merged**
